checks:
  php: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

tools:
  external_code_coverage:
    timeout: 600
