filter:
    excluded_paths:
        - "tests/*"
checks:
    php: true
build:
    environment:
            php:
                version: 7.4
    dependencies:
        before:
            - composer install
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover